version: '3.1'

services:
  # redis:
  #   image: redis:alpine
  #   container_name: redis
  #   restart: always
  #   mem_limit: 256m
  #   ports:
  #     - 6379:6379

  pqsql:
    container_name: postgres
    image: postgres:15-alpine
    mem_limit: 512m
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: synapse
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_INITDB_ARGS: "--encoding='UTF8' --lc-collate='C' --lc-ctype='C'"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
