name: '[Auth] Lint and test'

on:
  push:
    paths:
      - 'apps/auth/**'
      - 'packages/**'
      - '.github/workflows/auth-*.yaml'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        node-version: [18.x]
        mongodb-version: [6.0]

    # services:
    #   postgres:
    #     image: postgres:15-alpine
    #     env:
    #       POSTGRES_USER: postgres
    #       POSTGRES_PASSWORD: password
    #     ports:
    #       - 5432:5432
    #     options: >-
    #       --health-cmd pg_isready
    #       --health-interval 10s
    #       --health-timeout 5s
    #       --health-retries 5
    # env:
    #   DATABASE_URL: postgres://postgres:password@localhost:5432/db

    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
          cache-dependency-path: './pnpm-lock.yaml'

      - run: pnpm install --ignore-scripts
      - run: pnpm --filter auth lint
      - run: pnpm --filter auth test
        env:
          CI: true

      # build depedencies
      - run: pnpm --filter toolkit build
      - run: pnpm --filter auth prisma:generate
      - run: pnpm --filter auth prishma:push
      # - run: pnpm --filter auth test:e2e
      #   env:
      #     CI: true
